# -*- coding: utf-8 -*-
"""HCL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m07ZnB1RxC0sBdRCjMWgp1-3mk4yl7zQ
"""

def longest_unique_sequence(arr):
    seen = set()
    left = 0
    max_length = 0

    for right in range(len(arr)):
        while arr[right] in seen:
            seen.remove(arr[left])
            left += 1

        seen.add(arr[right])
        max_length = max(max_length, right - left + 1)
    return max_length
arr = [1, 2, 3, 1, 4, 5]
print("Maximum length:", longest_unique_sequence(arr))

def max_subarray_sum(arr):
    current_sum = arr[0]
    max_sum = arr[0]

    for i in range(1, len(arr)):
        current_sum = max(arr[i], current_sum + arr[i])
        max_sum = max(max_sum, current_sum)

    return max_sum


arr = [-2, 3, 4, -1, 5, -6]
print("Maximum discount value:", max_subarray_sum(arr))

def trap_water(height):
    left = 0
    right = len(height) - 1

    left_max = 0
    right_max = 0
    water = 0

    while left < right:
        if height[left] < height[right]:

            if height[left] >= left_max:
                left_max = height[left]
            else:
                water += left_max - height[left]

            left += 1

        else:

            if height[right] >= right_max:
                right_max = height[right]
            else:
                water += right_max - height[right]

            right -= 1

    return water
height = [4, 2, 0, 3, 2, 5]
print("Trapped water:", trap_water(height))

def max_performance(scores):
    current = scores[0]
    maximum = scores[0]

    for i in range(1, len(scores)):
        current = max(scores[i], current + scores[i])
        maximum = max(maximum, current)

    return maximum


scores = [-2, 3, 4, -1, 5, -6]

print("Highest performance:", max_performance(scores))

def max_product(arr):
    maximum = arr[0]
    minimum = arr[0]
    result = arr[0]

    for i in range(1, len(arr)):

        if arr[i] < 0:
            maximum, minimum = minimum, maximum

        maximum = max(arr[i], maximum * arr[i])
        minimum = min(arr[i], minimum * arr[i])

        result = max(result, maximum)

    return result


arr = [2, 3, -2, 4]

print("Maximum product:", max_product(arr))

def longest_unique_purchases(arr):
    seen = set()
    left = 0
    maximum = 0

    for right in range(len(arr)):

        while arr[right] in seen:
            seen.remove(arr[left])
            left += 1

        seen.add(arr[right])

        maximum = max(maximum, right - left + 1)

    return maximum


products = [10, 20, 30, 10, 40, 50]

print("Longest unique sequence:", longest_unique_purchases(products))

def count_subarrays(arr, target):
    prefix_sum = 0
    count = 0

    frequency = {0: 1}

    for num in arr:
        prefix_sum += num

        if prefix_sum - target in frequency:
            count += frequency[prefix_sum - target]

        frequency[prefix_sum] = frequency.get(prefix_sum, 0) + 1

    return count


transactions = [1, 2, 3, 2, 1]
target = 5

print("Number of groups:", count_subarrays(transactions, target))

def group_skills(words):
    groups = {}

    for word in words:
        key = ''.join(sorted(word))

        if key not in groups:
            groups[key] = []

        groups[key].append(word)

    return list(groups.values())


words = ["eat", "tea", "tan", "ate", "nat", "bat"]

result = group_skills(words)

print("Skill groups:")

for group in result:
    print(group)

def longest_consecutive(arr):
    numbers = set(arr)
    longest = 0

    for num in numbers:

        # Start only if num-1 does not exist
        if num - 1 not in numbers:

            current = num
            length = 1

            while current + 1 in numbers:
                current += 1
                length += 1

            longest = max(longest, length)

    return longest


packets = [100, 4, 200, 1, 3, 2]

print("Longest consecutive sequence:", longest_consecutive(packets))

def merge_intervals(intervals):

    if not intervals:
        return []

    intervals.sort()

    merged = [intervals[0]]

    for current in intervals[1:]:

        last = merged[-1]

        if current[0] <= last[1]:
            last[1] = max(last[1], current[1])

        else:
            merged.append(current)

    return merged


appointments = [
    [1, 3],
    [2, 6],
    [8, 10],
    [9, 12]
]

result = merge_intervals(appointments)

print("Merged appointments:")

for interval in result:
    print(interval)